### ISSUE TITLE
How to use this alongside sonar-plsql

### ISSUE THREAD

**Issue by ssadeque464** [gretard/sonar-sql-plugin#26]
Hey,

The plugin works great. I was wondering if there is a possibility of this plugin working alongside [sonar-plsql](https://github.com/felipebz/zpa) 

I integrated both and during scan I get this error: 
![image](https://user-images.githubusercontent.com/60558361/147890339-530f82f2-8f9d-416c-b851-fa7c1c1ef763.png)

Sonarqube version: `8.9.5 LTS`
Sonar scanner CLI: `4.6.2.2472`

Thanks

**Comment by wjj1059** [comment]
版本不对

**Comment by gretard** [comment]
Please configure additional properties:

- When you want PLSQL plugin execution ( this will disable execution sql plugin):
`sonar.lang.patterns.sql=na`

- When you want SQL plugin execution ( this will disable pssql plugin): 
`sonar.lang.patterns.plsqlopen=na`
