### ISSUE TITLE
Updated grammars-v4 for better Azure Synapse Analytics support

### ISSUE THREAD

**Issue by grschneider** [gretard/sonar-sql-plugin#27]
I submitted a patch to grammars-v4 (https://github.com/antlr/grammars-v4/pull/2471) to get better support for Azure Synapse Analytics T-SQL.
How do these changes get into a release of this plugin?

**Comment by gretard** [comment]
Hi,

Great stuff :) will include this in the next release :)

**Comment by grschneider** [comment]
Very cool, thanks. Do you have a regular release schedule?

**Comment by gretard** [comment]
There is no regular release schedule, as this is open source project, maintained on free time. 

Please check the latest release at  - https://github.com/gretard/sonar-sql-plugin/releases/tag/1.2.4
