### ISSUE TITLE
What about syntax errors, how can we report these?

### ISSUE THREAD

**Issue by mvhaasteren** [gretard/sonar-sql-plugin#28]
Currently we are adding DB2 on z/OS sql syntax and rules support to this outstanding plugin. We use the antlr4 g4 grammar from Craig Schneiderwent (https://github.com/cschneid-the-elder/mapa) and that works perfectly. We even communicate with him to improve on the g4 grammar.

So the first tests with a few rules were a success. 
But we are missing the syntax error handling when parsing a faulty sql file. As I can see in the code between the sqlsensor and the dialect specific parsing, no errorlistener is used and hence no syntax errors are passed higher up. I even wonder how a parse error could be displayed in the sonarqube project dashboard.

Any ideas?

**Comment by gretard** [comment]
Hi,

Thanks for raising this issue. Will add a feature to report parsing errors in the next release. This feature was specifically turned off (not to spam console output) as not all used SQL grammars fully parse code (without errors). 

Meanwhile if you are building plugin locally - it could be possible to enable error listeners and check the output on console or even report them to sonar as issues. All kind of contributions are welcome :)

Greta

**Comment by mvhaasteren** [comment]
Thanks Greta,
Your thoughts were matching the ideas I had. I added an errorlistener to the db2 dialect parser, changed the BaseDialect by adding a list with syntax errors and added an SyntaxErrorsFiller class to store the errors by linking them to a dummy hardcoded rule with no implementation. This filler is called in the SQLSensor class. This I'm testing now.

If successful we will make a pull request to your project.

Issues I have is
1. How can I use the resources rules xml files to load rules defined here. I added a Db2RulesDefinition class which loads the rules in .src/main/resources/db2z-rules.xml ... but I do not see this class being used runtime wise and thus the rules are not used. And an explanation by sonarsource about RuleDefinitions is somewhat scarce. or better non exsistend. Just adding the class as extension to the plugin is not enough.
2. skip rules are only valid for sources from external tooling (code guard, code coverage and sqlcehck). The SQLSensor does nothing with the property to skip rules. Why?

Best regards,
Maarten.

**Comment by gretard** [comment]
Hi,

Basically you are adding a new SQL dialect support while custom rules setup and documentation was used to support custom user rules in the declarative format for the supported SQL dialects.

Therefore, as you are adding a new dialect steps are:
1. Generate parser and lexer in org.antlr.sql.dialects.* package, i.e. org.antlr.sql.dialects.db2
2. Create class DB2Dialect (similar as https://github.com/gretard/sonar-sql-plugin/blob/master/src/sonar-sql-plugin/src/main/java/org/antlr/sql/dialects/VSQLDialect.java) specifying which lexer/parser to use.
3. Register dialect at https://github.com/gretard/sonar-sql-plugin/blob/master/src/sonar-sql-plugin/src/main/java/org/antlr/sql/dialects/Dialects.java class
4. Create custom declarative rules similar as https://github.com/gretard/sonar-sql-plugin/blob/master/src/sonar-sql-plugin/src/main/java/org/antlr/sql/dialects/rules/VSQLRules.java
4. Register custom rules at 3. Register dialect at https://github.com/gretard/sonar-sql-plugin/blob/master/src/sonar-sql-plugin/src/main/java/org/antlr/sql/dialects/Dialects.java class

That's all - now your plugin rules should be reported.

**Comment by mvhaasteren** [comment]
Thanks Greta.
Almost there ... we try to combine 4 DB2 z/OS sql grammar files together, because otherwise we have to change the sqlsensor code to deal with this (sort of sub dialects).I just merged your latest master branch with our code and apart from xml, jaxb and jakarta issues, all seems to be OK.
I will raise another issue with some questions. This one can get closed.
