### ISSUE TITLE
java rules and xml custom rules get the default RuleType code_smell

### ISSUE THREAD

**Issue by mvhaasteren** [gretard/sonar-sql-plugin#29]
Hi Greta,

While testing the db2 z/os rules I noticed that the issues detected always get the type code_smell, although we defined the ruletype of a rule as being a bug.

I think that the first bug is located in the SQLRulesDefinition class ... an ".setType(RuleType.valueOf(rule.getRuleType()))" at line 32 is missing.

And I did not discover why the rules from the customrules xml file with ruletype bug are registered as being of type code_smell. Somehow the bug is not saved in sonarqube accordingly and falls back to the default setting, being a code_smell.

**Comment by gretard** [comment]
Hi, will check and fix in the upcoming release.
