### ISSUE TITLE
not support external sqlcheck(v1.3)

### ISSUE THREAD

**Issue by jackhj000** [gretard/sonar-sql-plugin#32]
sqlcheck v1.3 report changed, the sqlcheckreader.java in plugin need update.

[v1.3](https://github.com/jarulraj/sqlcheck/releases/tag/v1.3) [Latest](https://github.com/jarulraj/sqlcheck/releases/latest)
**Features:**

- Line numbers, https://github.com/jarulraj/sqlcheck/issues/24

- Reporting status code 1 when antipatterns found, https://github.com/jarulraj/sqlcheck/issues/22 and https://github.com/jarulraj/sqlcheck/issues/34

**Fixes:**

- Long queries causing hang, https://github.com/jarulraj/sqlcheck/issues/32

- False positives, https://github.com/jarulraj/sqlcheck/issues/37 and https://github.com/jarulraj/sqlcheck/issues/25

- Crash on create table statement, https://github.com/jarulraj/sqlcheck/issues/33

Windows support available by building from source on your machine, see README
contributor welcome to add Windows support to build pipeline - https://github.com/jarulraj/sqlcheck/issues/53

**Comment by gretard** [comment]
Thanks for update, will fix in the next release.
