### ISSUE TITLE
[Question] Coverage results not showing in SonarQube

### ISSUE THREAD

**Issue by VaughanJ** [gretard/sonar-sql-plugin#34]
Hi,

We are using the plugin (SqlCoverCore.dll) to generate a SQLCover report (Coverage.opencover.xml)
[Coverage.opencover.zip](https://github.com/gretard/sonar-sql-plugin/files/9959730/Coverage.opencover.zip) (Zipped for upload purpose)

From my untrained eyes, this report that is generated looks good. I can see from the Summary that the sequenceCoverage is at 33%.

`<Summary numSequencePoints="762" visitedSequencePoints="259" numBranchPoints="0" visitedBranchPoints="0" sequenceCoverage="33.989500999450684" branchCoverage="0.0" maxCyclomaticComplexity="0" minCyclomaticComplexity="0" />`

Now when calling SonarQube I pass this file with the following CLI call

` sonar-scanner  -D sonar.host.url=https://sonarqube.eu.xxxxx.xx-xxxxxxx.net -D sonar.login=sonarscanner -D sonar.Password=*****  -D sonar.projectKey=database.immobilization -D sonar.projectName=database.immobilization -D sonar.projectVersion=0.0.120-develop-120 -D sonar.sources='/vzc/bamboo/build-agent-home/xml-data/build-dir/AWSRMGDT-IMD-JOB1/_src' -D sonar.dynamicAnalysis=reuseReports -D sonar.projectBaseDir='/vzc/bamboo/build-agent-home/xml-data/build-dir/AWSRMGDT-IMD-JOB1/_src' -D sonar.exclusions='**/*.tsql' -D sonar.typescript.coverage.ignoreNotFound=true -D sonar.working.directory='/vzc/bamboo/build-agent-home/xml-data/build-dir/AWSRMGDT-IMD-JOB1/_tmp/scannerwork' -D sonar.javascript.node.maxspace=16384 -D sonar.verbose=true -D sonar.inclusions='**/*.sql' -D sonar.sql.tsql.sqlcover.report="/vzc/bamboo/build-agent-home/xml-data/build-dir/AWSRMGDT-IMD-JOB1/_tst/Coverage.opencover.xml" -D sonar.lang.patterns.tsql="**/*.tsql" -D sonar.lang.patterns.sql='**/*.sql' -D sonar.branch.name='develop' -D sonar.analysis.packageVersion=0.0.120-develop-120 `

When looking at the code coverage for the project i see

![image](https://user-images.githubusercontent.com/3703414/200536092-46712578-90b0-465d-a3e7-50c16c9003d4.png)

and overall code
![image](https://user-images.githubusercontent.com/3703414/200536207-6c6f83a4-a847-457f-af4f-f55e0c5668da.png)

Attached are the SQ Logfiles
[SonarqubeLogs.txt](https://github.com/gretard/sonar-sql-plugin/files/9970178/SonarqubeLogs.txt)

Additional information:
SQ Version: Version 9.7 (build 61563)

Plugin Version:
1.3.0

Settings:
![image](https://user-images.githubusercontent.com/3703414/200540406-0eb06f36-480b-4c9a-a98d-cabe9cfa3361.png)

![image](https://user-images.githubusercontent.com/3703414/200540424-813ef95f-b721-4641-82f9-6d7668ca85c0.png)

![image](https://user-images.githubusercontent.com/3703414/200540462-ec2939c8-7495-45bf-8517-319bae8cb1f6.png)

![image](https://user-images.githubusercontent.com/3703414/200540486-f3c31cb5-c2d6-4478-9b6b-c45e4b48ec0e.png)

All of our SQL Scripts have the suffix SQL and not TSQL, but as all we want the plugin for is to show the code coverage, so I assume the following settings are ok:

sonar.sql.file.suffixes=.sqldisable
sonar.sql.dialect=tsql

Any help appreciated, as we seem unable to fix this ourselves.

Thanks
Jon

**Comment by gretard** [comment]
Hi,
From logs it seems that coverage file is not picked up by the plugin as it does not exist in the current working dir. Could you specify property **sonar.sql.tsql.sqlcover.report** with the full path of the report, for example:

`sonar.sql.tsql.sqlcover.report=c:/build/1/out/Coverage.opencoverxml`

Will include more thorough logging of this sensor in the upcoming release, so that it is easier to debug.

**Comment by VaughanJ** [comment]
The full path is specified:
sonar.sql.tsql.sqlcover.report="/vzc/bamboo/build-agent-home/xml-data/build-dir/AWSRMGDT-IMD-JOB1/_tst/Coverage.opencover.xml"

I can drop the file into the current working directory if we think it is more likely to be picked up?

**Comment by gretard** [comment]
Yes please, will double check.

**Comment by VaughanJ** [comment]
I also don't know if it's worth mentioned, but this is run on a Linux build server, so all paths will be Linux based.
