### ISSUE TITLE
Question: Why not generating java from antlr4 grammar-g4 files?

### ISSUE THREAD

**Issue by mvhaasteren** [gretard/sonar-sql-plugin#35]
Hi Greta,

The DB2 z/OS sql dialect we have added to our fork is based on the grammar files of Craig his implementation (see db2 at https://github.com/cschneid-the-elder/mapa).
We use the antlr4 maven plugin to generate the corresponding java objects. This is really very convenient!

question:
Why do you not use it for all the current available dialects? You did document the url's to the grammar sources nicely, so why not use it?

Best regards,
Maarten.

**Comment by gretard** [comment]
Hi, 
I am not generating for all available dialects as generated classes differ and plugin would need updates to support required features - plugin sql rules, complexity and highlighting.

**Comment by mvhaasteren** [comment]
I concur ... it means refactoring and is time intensive. But beneficial result is clean and up-to-date code :-).

**Comment by gretard** [comment]
Maybe there are some other libraries for this purpose? :)
