### ISSUE TITLE
In the violationsearcher a mix is made between siblings and parents

### ISSUE THREAD

**Issue by mvhaasteren** [gretard/sonar-sql-plugin#39]
Hi Greta,

See https://github.com/gretard/sonar-sql-plugin/blob/54495ab6fa18702e4689ae7619d6a547bdfd8f89/src/sonar-sql-plugin/src/main/java/org/antlr/sql/sca/ViolationsSearcher2.java#L93

Am I wrong to see that traversiong the siblings here a mix is made with the getParents?

**Comment by gretard** [comment]
Thanks for raising this - yes it is a bug and will be fixed in the next version.
