### ISSUE TITLE
Add ability to ignore some SQL Code Guard rules

### ISSUE THREAD

**Issue by olsh** [gretard/sonar-sql-plugin#4]
It would be nice to have an option to ignore some rules produced by third party analyzers like SQL Code Guard and SQL Check.
So, for instance, I'd like to disable only `Hint usage` rule and keep other rules.

**Comment by gretard** [comment]
Will include this in the upcoming release.

**Comment by gretard** [comment]
Added option _sonar.sql.rules.skip_, allowing to specify _repoKey:ruleId_ which for rules you want to skip reporting:

```
sonar.sql.rules.skip=tsql-cg:ST008
```

**Comment by olsh** [comment]
Thank you 👍

**Comment by jpbruckart** [comment]
Should the comma separated list  look like:

tsql-cg:EI016,tsql-cg:MI007,tsql-cg:PE006,tsql-cg:PE008,tsql-cg:PE010,tsql-cg:PE012,tsql-cg:PE021,tsql-cg:ST011

or

tsql-cg:EI016,MI007,PE006,PE008,PE010,PE012,PE021,ST011 

??

**Comment by gretard** [comment]
Hi, the first one - tsql-cg:EI016,tsql-cg:MI007,tsql-cg:PE006,tsql-cg:PE008,tsql-cg:PE010,tsql-cg:PE012,tsql-cg:PE021,tsql-cg:ST011
