### ISSUE TITLE
support for Sonar 10.X

### ISSUE THREAD

**Issue by ddaz** [gretard/sonar-sql-plugin#42]
with sonar 10, they think : https://docs.sonarsource.com/sonarqube/10.2/user-guide/clean-code/    when a put some rules, now appear  some tags in the rules , we need to change something?.
![iisue](https://github.com/gretard/sonar-sql-plugin/assets/5024817/41d3de5d-62f7-4cdc-879e-66541a3e4b1b)

**Comment by gretard** [comment]
Hi,

Thanks for raising this, but this is not an issue. These tags can be used for rules filtering.
