### ISSUE TITLE
can't seem to get custom rule to work

### ISSUE THREAD

**Issue by dreamsie** [gretard/sonar-sql-plugin#6]
Hello, I'm trying to create a custom rule that require nolock.  I have tried many ways and can't seem to get it to work.  It should be fairly simple but it's not working.  Below is the simplest ones that I made that I thought should work.  Any helps would be appreciated! Thank you in advance!
 ` <rule>
        <key>CC101</key>
        <name>nolock hint is not being used</name>
        <internalKey>CC101</internalKey>
        <descriptionFormat>HTML</descriptionFormat>
        <description>nolock hint is not being used</description>
        <severity>BLOCKER</severity>
        <cardinality>SINGLE</cardinality>
        <ruleImplementation>
            <names>
                <textItem>Table_hintContext</textItem>
            </names>
            <textToFind>
                <textItem>NOLOCK</textItem>
            </textToFind>
            <parentRules/>
            <childrenRules/>
            <siblingsRules/>
            <usesRules/>
            <ruleViolationMessage>Nolock is not being used</ruleViolationMessage>
            <times>0</times>
            <ruleMode>Default</ruleMode>
            <ruleMatchType>TextAndClass</ruleMatchType>
            <ruleResultType>FailIfNotFound</ruleResultType>
            <textCheckType>Contains</textCheckType>
            <usesRules/>
        </ruleImplementation>
    </rule>`

**Comment by gretard** [comment]
Hello,

I would suggest trying this way:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<sql-rules repoName="Demo adhoc rules for TSQL"
	repoKey="tsqlCustom" isAdhoc="true">
	<rule>
		<key>CC101</key>
		<name>nolock hint is not being used</name>
		<internalKey>CC101</internalKey>
		<descriptionFormat>HTML</descriptionFormat>
		<description>nolock hint is not being used</description>
		<severity>BLOCKER</severity>
		<cardinality>SINGLE</cardinality>
		<ruleImplementation>
			<names>
				<textItem>Select_statementContext</textItem>
			</names>
			<childrenRules>
				<ruleImplementation>
					<names>
						<textItem>Table_hintContext</textItem>
					</names>
					<textToFind>
						<textItem>NOLOCk</textItem>
					</textToFind>
					<ruleMatchType>ClassAndText</ruleMatchType>
					<ruleResultType>FailIfNotFound</ruleResultType>
					<textCheckType>Default</textCheckType>
					<ruleMatchType>Default</ruleMatchType>
				</ruleImplementation>
			</childrenRules>
			<ruleViolationMessage>Nolock is not being used</ruleViolationMessage>
			<ruleMatchType>ClassOnly</ruleMatchType>
			<violatingRulesCodeExamples>
				<ruleCodeExample>SELECT * from dbo.test;</ruleCodeExample>
			</violatingRulesCodeExamples>
			<compliantRulesCodeExamples>
				<ruleCodeExample>SELECT * from dbo.test WITH (NOLOCK);
				</ruleCodeExample>
			</compliantRulesCodeExamples>
		</ruleImplementation>
	</rule>
</sql-rules>
```

The thing is that at first rules engine tries to find all nodes matching the first main rule(ruleImplementation: Select_statementContext), and then check if they violate or no any rules. 

In your example you try to find Table_hintContext. If there are none, i.e. SELECT * FROM dbo.test, then rules engine does not have  what to analyze, and this contradicts with what you are asking - fail if not found as engine does not have what to analyze. Maybe in the future I will try to investigate this and update engine to support these kind of cases as well. 

Anyway, I have rewritten rule, so that at first it tries to find all select statements and checks if they contain tablehints with NOLOCK, if no - then rule will report an error :) 

Hope this helps :)

**Comment by dreamsie** [comment]
Thank you so much! That fixed the issue I was having. Thank you for explaining how the rule engine works. I was thinking along that line and had something similar but I didn't realize I can put another ruleImplementation inside the sibling node.  
Thank you again for your quick response!  And thank you for the awesome open source plugin!!
