### ISSUE TITLE
Custom Rules with variable search parameter and debtRemediationFunctionCoefficient

### ISSUE THREAD

**Issue by tgov01** [gretard/sonar-sql-plugin#7]
Note:  Issue copied from https://github.com/gretard/sonar-tsql-plugin/issues/26

Is it possible to have a custom rule with variable search parameter... (textToFind). What I'm looking to do is tie back a table's name to the parent name of the table being updated (Ddl_objectContext). If the parent is being updated, skip the rule. Basically, the rule is to look for tables not using "WITH (NOLOCK)".

Update T1
Set Col1 = T2.Col1
From dbo.Table1 T1 Inner Join dbo.Table2 T2 WITH (NOLOCK)
On T1.Col1 = T2.Col1

Basically, Table1 doesn't need the NOLOCK because it is being updated, but Table2 should use the NOLOCK table hint.

Additionally, I noticed that debtRemediationFunctionCoefficient is not working for me. As I understand it, this is supposed to show the amount of work required to remediate the issue. This is showing as "0min effort" even though that node is present.

`<remediationFunction>LINEAR</remediationFunction>`
`<debtRemediationFunctionCoefficient>2min</debtRemediationFunctionCoefficient>`

Thanks in advance for any help you could provide.

Implementation file included in attachment.

[TSQL.txt](https://github.com/gretard/sonar-sql-plugin/files/3730216/TSQL.txt)

**Comment by gretard** [comment]
Hi,

I would suggest starting by parsing each dml statement separately, at first find all Sql_clauseContext, then based on that look into children. Maybe something like this:

```
<ruleImplementation>
			<names>
				<textItem>Sql_clauseContext</textItem>
			</names>
			<childrenRules>
				<ruleImplementation>
					<names>
						<textItem>Select_statementContext</textItem>
						<textItem>Delete_statementContext</textItem>
						<textItem>Update_statementContext</textItem>
						<textItem>Merge_statementContext</textItem>
						<textItem>Insert_statementContext</textItem>
					</names>
					<childrenRules>
						<ruleImplementation>
							<names>
								<textItem>
									<textItem>Table_source_itemContext</textItem>
								</textItem>
							</names>
							<childrenRules>
								<ruleImplementation>
									<names>
										<textItem>With_table_hintsContext</textItem>
									</names>
									<indexCheckType>Default</indexCheckType>
									<distanceCheckType>Default</distanceCheckType>
									<ruleMatchType>ClassOnly</ruleMatchType>
									<ruleResultType>FailIfNotFound</ruleResultType>
									<textCheckType>Default</textCheckType>
								</ruleImplementation>
							</childrenRules>
							<ruleViolationMessage>test</ruleViolationMessage>
							<indexCheckType>Default</indexCheckType>
							<distanceCheckType>Default</distanceCheckType>
							<ruleMatchType>ClassOnly</ruleMatchType>
							<ruleResultType>Default</ruleResultType>
							<textCheckType>Default</textCheckType>
						</ruleImplementation>
					</childrenRules>
					<indexCheckType>Default</indexCheckType>
					<distanceCheckType>Default</distanceCheckType>
					<ruleMatchType>ClassOnly</ruleMatchType>
					<ruleResultType>Default</ruleResultType>
					<textCheckType>Default</textCheckType>
				</ruleImplementation>
			</childrenRules>
			<indexCheckType>Default</indexCheckType>
			<distanceCheckType>Default</distanceCheckType>
			<ruleMatchType>ClassOnly</ruleMatchType>
			<ruleResultType>Default</ruleResultType>
			<textCheckType>Default</textCheckType>
			<violatingRulesCodeExamples>
				<ruleCodeExample>Select DistributorID, FirstName, LastName From
					dbo.Distributor D;
				</ruleCodeExample>
				<ruleCodeExample>with cte as (Select DistributorID, FirstName,
					LastName From
					dbo.Distributor) select * from cte;
				</ruleCodeExample>
			</violatingRulesCodeExamples>
			<compliantRulesCodeExamples>
				<ruleCodeExample>Select DistributorID, FirstName, LastName From
					dbo.Distributor D WITH (NOLOCK);
				</ruleCodeExample>
				<ruleCodeExample>with cte as (Select DistributorID, FirstName,
					LastName From
					dbo.Distributor D WITH (NOLOCK)) select * from cte;
				</ruleCodeExample>
			</compliantRulesCodeExamples>
		</ruleImplementation>
```

**Comment by gretard** [comment]
And with regards to debtRemediationFunctionCoefficient  - there is a catch that your custom rules are reported as adhoc and SonarQube does not support adding this. If there is a need for commercial plugin support you can ping me on gitter :)

**Comment by tgov01** [comment]
Thanks for your response back.  After taking out the extra itemText node from Table_source_itemContext, and adding SkipIfNotFound to this, and changing With_table_hintsContext to Table_hintContext adding `<textToFind>NoLock</textToFind>`, I'm still not getting what I'm looking for.

I think that I'd need to start at the Table_source_itemContext because this is the item that I want highlighted.  Ideally, for the sample below, I would want the ones marked with "Offending table not using NOLOCK" to be the offending items not using hint "With (NoLock)" to be violating the rules.

	;With CTE As
	(
		Select PK_FileType
		From dbo.FileType -- Offending table not using NOLOCK
	)
	Select PK_FileType From CTE

	;With CTE As
	(
		Select PK_FileType
		From dbo.FileType With (NoLock)
	)
	Select PK_FileType From CTE

	Update dbo.FileType
	Set PK_FileType = 1
	From dbo.FileType F -- Should not be highlight because it is item being updated
		Inner Join dbo.FileAddress A -- Offending table not using NOLOCK
			On F.PK_FileType = A.PK_FileType

	Update F
	Set PK_FileType = 1
	From dbo.FileType F -- Should not be highlight because it is item being updated
		Inner Join dbo.FileAddress A -- Offending table not using NOLOCK
			On F.PK_FileType = A.PK_FileType

	Update dbo.FileType
	Set PK_FileType = 1
	From dbo.FileType F -- Should not be highlight because it is item being updated
		Inner Join dbo.FileAddress A With (NoLock)
			On F.PK_FileType = A.PK_FileType

	Update F
	Set PK_FileType = 1
	From dbo.FileType F -- Should not be highlight because it is item being updated
		Inner Join dbo.FileAddress A With (NoLock)
			On F.PK_FileType = A.PK_FileType

**Comment by gretard** [comment]
Hi, I have actually found a small bug with uses rules. You can download snapshot version from (https://dev.azure.com/kgreta/sonar-sql-plugin/_build/results?buildId=75&view=results), for example [this](https://dev.azure.com/kgreta/2319744a-731b-48e3-81da-94790c701078/_apis/build/builds/75/artifacts?artifactName=build-Linux&api-version=5.2-preview.5&%24format=zip).

Then I would suggest trying something like this, otherwise I am thinking you might need to split rule into separate ones or raise Feature Request :) :

```
	<ruleImplementation>
			<names>
				<textItem>Table_source_itemContext</textItem>
			</names>
			<textToFind>
			</textToFind>
			<parentRules>
				<ruleImplementation>
					<names>
						<textItem>Join_partContext</textItem>
						<textItem>Select_statementContext</textItem>
					</names>
					<textToFind>
					</textToFind>
					<parentRules>
					</parentRules>
					<childrenRules>
						<ruleImplementation>
							<names>
								<textItem>With_table_hintsContext</textItem>
							</names>
							<textToFind>
							</textToFind>
							<parentRules>
							</parentRules>
							<childrenRules>
							</childrenRules>
							<siblingsRules>
							</siblingsRules>
							<usesRules>
							</usesRules>
							<ruleViolationMessage>HINTS</ruleViolationMessage>
							<times>0</times>
							<distance>0</distance>
							<index>0</index>
							<indexCheckType>Default</indexCheckType>
							<distanceCheckType>Default</distanceCheckType>
							<ruleMode />
							<ruleMatchType>ClassOnly</ruleMatchType>
							<ruleResultType>FailIfNotFound</ruleResultType>
							<textCheckType>Default</textCheckType>
						</ruleImplementation>
					</childrenRules>
					<siblingsRules>
					</siblingsRules>
					<usesRules>
					</usesRules>
					<ruleViolationMessage>MAINSELECTS</ruleViolationMessage>
					<times>0</times>
					<distance>0</distance>
					<index>0</index>
					<indexCheckType>Default</indexCheckType>
					<distanceCheckType>Default</distanceCheckType>
					<ruleMode />
					<ruleMatchType>ClassOnly</ruleMatchType>
					<ruleResultType>SkipIfNotFound</ruleResultType>
					<textCheckType>Default</textCheckType>
					<violatingRulesCodeExamples>
						<ruleCodeExample />
					</violatingRulesCodeExamples>
					<compliantRulesCodeExamples>
						<ruleCodeExample />
					</compliantRulesCodeExamples>
				</ruleImplementation>
			</parentRules>
			<childrenRules>
			</childrenRules>
			<siblingsRules>
			</siblingsRules>
			<usesRules>

				<ruleImplementation>
					<names>
						<textItem>IdContext</textItem>
					</names>
					<textToFind>
					</textToFind>
					<parentRules>

						<ruleImplementation>
							<names>
								<textItem>Common_table_expressionContext</textItem>
							</names>
							<textToFind>
							</textToFind>
							<parentRules>
							</parentRules>
							<childrenRules>
							</childrenRules>
							<siblingsRules>
							</siblingsRules>
							<usesRules>
							</usesRules>
							<ruleViolationMessage>CTE</ruleViolationMessage>
							<times>0</times>
							<distance>1</distance>
							<index>0</index>
							<indexCheckType>Default</indexCheckType>
							<distanceCheckType>Equals</distanceCheckType>
							<ruleMode />
							<ruleMatchType>Default</ruleMatchType>
							<ruleResultType>SkipIfFound</ruleResultType>
							<textCheckType>Default</textCheckType>
						</ruleImplementation>

					</parentRules>
					<childrenRules>
					</childrenRules>
					<siblingsRules>
					</siblingsRules>
					<usesRules>
					</usesRules>
					<ruleViolationMessage>ID</ruleViolationMessage>
					<times>0</times>
					<distance>0</distance>
					<index>0</index>
					<indexCheckType>Default</indexCheckType>
					<distanceCheckType>Default</distanceCheckType>
					<ruleMode />
					<ruleMatchType>Full</ruleMatchType>
					<ruleResultType>Default</ruleResultType>
					<textCheckType>Default</textCheckType>
				</ruleImplementation>
			</usesRules>
			<ruleViolationMessage>MAIN</ruleViolationMessage>
			<times>0</times>
			<distance>0</distance>
			<index>0</index>
			<indexCheckType>Default</indexCheckType>
			<distanceCheckType>Default</distanceCheckType>
			<ruleMode />
			<ruleMatchType>ClassOnly</ruleMatchType>
			<ruleResultType>Default</ruleResultType>
			<textCheckType>Default</textCheckType>
			<violatingRulesCodeExamples>
				<ruleCodeExample><![CDATA[
				;With CTE As
(
	Select PK_FileType
	From dbo.FileType 
)
Select PK_FileType From CTE
				]]>
				 </ruleCodeExample>
				 	<ruleCodeExample><![CDATA[

Update dbo.FileType
Set PK_FileType = 1
From dbo.FileType F 
	Inner Join dbo.FileAddress A 
		On F.PK_FileType = A.PK_FileType
				]]>
				 </ruleCodeExample>
				 	 
			</violatingRulesCodeExamples>
			<compliantRulesCodeExamples>
					<ruleCodeExample><![CDATA[
				;With CTE As
(
	Select PK_FileType
	From dbo.FileType   With (NoLock)
)
Select PK_FileType From CTE
				]]>
				 </ruleCodeExample>
				 
				<ruleCodeExample><![CDATA[
				Update F
Set PK_FileType = 1
From dbo.FileType F 
	Inner Join dbo.FileAddress A  With (NoLock)
		On F.PK_FileType = A.PK_FileType
				]]>
				 </ruleCodeExample>
			</compliantRulesCodeExamples>
		</ruleImplementation>
```

**Comment by tgov01** [comment]
I'm looking into this right now.  Thanks again for your response.  I'll post my findings.

**Comment by tgov01** [comment]
After updating to the 1.0.4 version that was provided...

2019-10-18T20:05:32.2444965Z 20:05:32.243 INFO: Load/download plugins (done) | time=242ms
2019-10-18T20:05:32.5481329Z 20:05:32.546 DEBUG: Plugins:
2019-10-18T20:05:32.5481965Z 20:05:32.547 DEBUG:   * SonarCSS 1.1.1.1010 (cssfamily)
2019-10-18T20:05:32.5482269Z 20:05:32.547 DEBUG:   * Svn 1.9.0.1295 (scmsvn)
2019-10-18T20:05:32.5482508Z 20:05:32.547 DEBUG:   * SQL language plugin **1.0.4** (sql)

I'm getting the following error from SQ.  Any ideas?

2019-10-18T20:01:38.0243229Z java.lang.NoClassDefFoundError: org/sonar/api/internal/apachecommons/lang/StringUtils
2019-10-18T20:01:38.0243556Z 	at org.antlr.sql.sca.nodes.ParseTreeNode.getUses(ParseTreeNode.java:104)
2019-10-18T20:01:38.0243844Z 	at org.antlr.sql.sca.ViolationsSearcher.visit(ViolationsSearcher.java:64)
2019-10-18T20:01:38.0244146Z 	at org.antlr.sql.sca.ViolationsSearcher.search(ViolationsSearcher.java:21)
2019-10-18T20:01:38.0244426Z 	at org.antlr.sql.sca.IssuesProvider.analyze(IssuesProvider.java:35)
2019-10-18T20:01:38.0244720Z 	at org.sonar.plugins.sql.fillers.IssuesFiller.fill(IssuesFiller.java:22)
2019-10-18T20:01:38.0245001Z 	at org.sonar.plugins.sql.sensors.SQLSensor$1.run(SQLSensor.java:83)
2019-10-18T20:01:38.0245313Z 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1409)
2019-10-18T20:01:38.0245611Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
2019-10-18T20:01:38.0245919Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
2019-10-18T20:01:38.0246581Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)

**Comment by gretard** [comment]
Thanks for reporting this. This was fixed in https://github.com/gretard/sonar-sql-plugin/releases/tag/1.0.5
